[project]
name = "cos-585"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Keith Murray", email = "murraykeith64@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
cos-585 = "cos_585:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
